const animeList = [
    {
        id: "wind-breaker",
        title: "Wind Breaker (Hindi Dub)",
        poster: "https://image.tmdb.org/t/p/w500/f0CZzRXyqCc41NePDJSY23YQ2SS.jpg",
        year: "2024",
        duration: "24m",
        rating: "7.72",
        genres: "Action, Anime, School",
        cast: "Koki Uchiyama, Nobunaga Shimazaki",
        description: "Haruka Sakura wants nothing to do with weaklings—he's only interested in the strongest of the strong. He's just started at Furin High School...",
        seasons: [
            {
                name: "Season 1",
                server1: [
                    "https://vidmoly.net/embed-otx0kv0uyysp.html",
                    "https://vidmoly.net/embed-w3aof5xz648a.html",
                    "https://vidmoly.net/embed-xbla97mxraw2.html",
                    "https://vidmoly.net/embed-7xp0m9w2mdkl.html",
                    "https://vidmoly.net/embed-twu8lb79askx.html",
                    "https://vidmoly.net/embed-sben16btq6f6.html",
                    "https://vidmoly.net/embed-moc619ek69l3.html",
                    "https://vidmoly.net/embed-7izjyy8qzus5.html",
                    "https://vidmoly.net/embed-zzz54lpwl95b.html",
                    "https://vidmoly.net/embed-ifgpim3e87dx.html",
                    "https://vidmoly.net/embed-f95f3jc15soc.html",
                    "https://vidmoly.net/embed-kg3uzhpbusrn.html",
                    "https://vidmoly.net/embed-9zd0zlr2ky26.html"
                ],
                server2: [] // Isme links nahi hain, toh button nahi dikhega
            }
        ]
    },

    {
        id: "solo-leveling",
        title: "Solo Leveling (Hindi Dubbed)",
        poster: "https://image.tmdb.org/t/p/w500/rsOApVLbIQEcNkqSlOxNPyg3FyI.jpg",
        year: "2024",
        duration: "24m",
        rating: "8.7",
        genres: "Action, Adventure, Fantasy",
        cast: "Taito Ban, Reina Ueda",
        description: "In a world where hunters must battle deadly monsters to protect mankind, Sung Jinwoo, a notoriously weak hunter, finds himself in a struggle for survival.",
        seasons: [
            {
                name: "Season 1",
                server1: [
                    "https://animehindiworld.seekplays.com/#kcaxn",
                    "https://animehindiworld.seekplays.com/#ia65p",
                    "https://animehindiworld.seekplays.com/#3ubig",
                    "https://animehindiworld.seekplays.com/#ia65v",
                    "https://animehindiworld.seekplays.com/#wzdm6",
                    "https://animehindiworld.seekplays.com/#5t9ll",
                    "https://animehindiworld.seekplays.com/#ia6ij",
                    "https://animehindiworld.seekplays.com/#kcaky",
                    "https://animehindiworld.seekplays.com/#pwyov",
                    "https://animehindiworld.seekplays.com/#6evp5",
                    "https://animehindiworld.seekplays.com/#8ha56",
                    "https://animehindiworld.seekplays.com/#ajmbe"
                ],
                server2: []
            }
        ]
    },
{
    "id": "haikyuu",
    "title": "Haikyuu!!",
    "poster": "https://image.tmdb.org/t/p/w500/rm39VFnu0giTTccK0vSsPsKiatj.jpg",
    "year": "2014",
    "duration": "24m",
    "rating": "8.7",
    "genres": "Animation, Comedy, Drama, Sport",
    "description": "Inspired after watching a volleyball ace nicknamed 'Little Giant' in action, small-statured Shouyou Hinata revives the volleyball club at his middle school. The newly-formed team even makes it to a tournament; however, their first match turns out to be their last when they are brutally squashed by the 'King of the Court,' Tobio Kageyama.",
    "seasons": [
        {
            "name": "Season 1",
            "server1": [
                "https://animehindiworld.seekplays.com/#iuusx",
                "https://animehindiworld.seekplays.com/#bwwgu",
                "https://animehindiworld.seekplays.com/#nrrf6",
                "https://animehindiworld.seekplays.com/#6mmot",
                "https://animehindiworld.seekplays.com/#kss3x",
                "https://animehindiworld.seekplays.com/#cbb9t",
                "https://animehindiworld.seekplays.com/#o11wt",
                "https://animehindiworld.seekplays.com/#kss38",
                "https://animehindiworld.seekplays.com/#jvvma",
                "https://animehindiworld.seekplays.com/#h66ax",
                "https://animehindiworld.seekplays.com/#399tf",
                "https://animehindiworld.seekplays.com/#h66aq",
                "https://animehindiworld.seekplays.com/#wqqyw",
                "https://animehindiworld.seekplays.com/#tjjby",
                "https://animehindiworld.seekplays.com/#spp6p",
                "https://animehindiworld.seekplays.com/#eff11",
                "https://animehindiworld.seekplays.com/#5aasu",
                "https://animehindiworld.seekplays.com/#vddqs",
                "https://animehindiworld.seekplays.com/#lttc9",
                "https://animehindiworld.seekplays.com/#mzzy8",
                "https://animehindiworld.seekplays.com/#gyyvx",
                "https://animehindiworld.seekplays.com/#uggjm",
                "https://animehindiworld.seekplays.com/#aoop1",
                "https://animehindiworld.seekplays.com/#8cc3h",
                "https://animehindiworld.seekplays.com/#xhhi5"
            ],
            "server2": []
        },
        {
            "name": "Season 2",
            "server1": [
                "https://animehindiworld.seekplays.com/#h66ur",
                "https://animehindiworld.seekplays.com/#h66u8",
                "https://animehindiworld.seekplays.com/#sppb9",
                "https://animehindiworld.seekplays.com/#399az",
                "https://animehindiworld.seekplays.com/#iuut8",
                "https://animehindiworld.seekplays.com/#5aasw",
                "https://animehindiworld.seekplays.com/#1xxr6",
                "https://animehindiworld.seekplays.com/#xhh3i",
                "https://animehindiworld.seekplays.com/#o11na",
                "https://animehindiworld.seekplays.com/#nrrzb",
                "https://animehindiworld.seekplays.com/#jvvwu",
                "https://animehindiworld.seekplays.com/#kssh8",
                "https://animehindiworld.seekplays.com/#iuut1",
                "https://animehindiworld.seekplays.com/#gyy18",
                "https://animehindiworld.seekplays.com/#o11vu",
                "https://animehindiworld.seekplays.com/#9eeg1",
                "https://animehindiworld.seekplays.com/#ltts6",
                "https://animehindiworld.seekplays.com/#8cchc",
                "https://animehindiworld.seekplays.com/#uggow",
                "https://animehindiworld.seekplays.com/#399uq",
                "https://animehindiworld.seekplays.com/#h669k",
                "https://animehindiworld.seekplays.com/#iuuak",
                "https://animehindiworld.seekplays.com/#8cchm",
                "https://animehindiworld.seekplays.com/#5aat9",
                "https://animehindiworld.seekplays.com/#sppbj"
            ],
            "server2": []
        }
    ]
},
{
    "id": "naruto",
    "title": "Naruto",
    "poster": "https://image.tmdb.org/t/p/w500/xppeysfvDKVx775MFuH8Z9BlpMk.jpg",
    "year": "2002",
    "duration": "23m",
    "rating": "8.4",
    "genres": "Action, Adventure, Fantasy",
    "description": "Naruto Uzumaki, a mischievous adolescent ninja, struggles as he searches for recognition and dreams of becoming the Hokage, the village's leader and strongest ninja.",
    "seasons": [
        {
            "name": "Season 1",
            "server1": [
                "https://animehindiworld.seekplays.com/#jvwtk",
                "https://animehindiworld.seekplays.com/#nrzb5",
                "https://animehindiworld.seekplays.com/#ltcfk",
                "https://animehindiworld.seekplays.com/#h6uxe",
                "https://animehindiworld.seekplays.com/#5asqu",
                "https://animehindiworld.seekplays.com/#bwehk",
                "https://animehindiworld.seekplays.com/#8c3yt",
                "https://animehindiworld.seekplays.com/#gyvuw",
                "https://animehindiworld.seekplays.com/#1xro5",
                "https://animehindiworld.seekplays.com/#pnmsm",
                "https://animehindiworld.seekplays.com/#h6udw",
                "https://animehindiworld.seekplays.com/#vdqjd",
                "https://animehindiworld.seekplays.com/#kshfn",
                "https://animehindiworld.seekplays.com/#jvws8",
                "https://animehindiworld.seekplays.com/#ugj5t",
                "https://animehindiworld.seekplays.com/#9eoi9",
                "https://animehindiworld.seekplays.com/#iutrn",
                "https://animehindiworld.seekplays.com/#aop5b",
                "https://animehindiworld.seekplays.com/#o1ntx",
                "https://animehindiworld.seekplays.com/#8c31z",
                "https://animehindiworld.seekplays.com/#39ado",
                "https://animehindiworld.seekplays.com/#bwecl",
                "https://animehindiworld.seekplays.com/#6mgh8",
                "https://animehindiworld.seekplays.com/#sp68i",
                "https://animehindiworld.seekplays.com/#mzy6n",
                "https://animehindiworld.seekplays.com/#h6uxn"
            ],
            "server2": []
        },
        {
            "name": "Season 2",
            "server1": [
                "https://animehindiworld.seekplays.com/#ltcxh",
                "https://animehindiworld.seekplays.com/#1xrwc",
                "https://animehindiworld.seekplays.com/#bwea3",
                "https://animehindiworld.seekplays.com/#9eoto",
                "https://animehindiworld.seekplays.com/#gyvpy",
                "https://animehindiworld.seekplays.com/#6mgt5",
                "https://animehindiworld.seekplays.com/#kshry",
                "https://animehindiworld.seekplays.com/#vdqml",
                "https://animehindiworld.seekplays.com/#39alw",
                "https://animehindiworld.seekplays.com/#mzyof",
                "https://animehindiworld.seekplays.com/#8c3r6",
                "https://animehindiworld.seekplays.com/#pnm91",
                "https://animehindiworld.seekplays.com/#5as8p",
                "https://animehindiworld.seekplays.com/#tjbhe",
                "https://animehindiworld.seekplays.com/#xhizq",
                "https://animehindiworld.seekplays.com/#6mmjs",
                "https://animehindiworld.seekplays.com/#cb95l",
                "https://animehindiworld.seekplays.com/#iut8y",
                "https://animehindiworld.seekplays.com/#ugjsb",
                "https://animehindiworld.seekplays.com/#5as83",
                "https://animehindiworld.seekplays.com/#sp6ii",
                "https://animehindiworld.seekplays.com/#h6u5v",
                "https://animehindiworld.seekplays.com/#bwwoa",
                "https://animehindiworld.seekplays.com/#ef1po",
                "https://animehindiworld.seekplays.com/#iutkg",
                "https://animehindiworld.seekplays.com/#sp6is"
            ],
            "server2": []
        },
        {
            "name": "Season 3",
            "server1": [
                "https://animehindiworld.seekplays.com/#sp6hh",
                "https://animehindiworld.seekplays.com/#5aslo",
                "https://animehindiworld.seekplays.com/#mzyeq",
                "https://animehindiworld.seekplays.com/#h6u3y",
                "https://animehindiworld.seekplays.com/#jvwpc",
                "https://animehindiworld.seekplays.com/#ugjaj",
                "https://animehindiworld.seekplays.com/#tjbsw",
                "https://animehindiworld.seekplays.com/#vdqni",
                "https://animehindiworld.seekplays.com/#kshxq",
                "https://animehindiworld.seekplays.com/#1xrvt",
                "https://animehindiworld.seekplays.com/#nrzwa",
                "https://animehindiworld.seekplays.com/#gyvoz",
                "https://animehindiworld.seekplays.com/#cb93i",
                "https://animehindiworld.seekplays.com/#pnmbf",
                "https://animehindiworld.seekplays.com/#8c3xp",
                "https://animehindiworld.seekplays.com/#h6u3q",
                "https://animehindiworld.seekplays.com/#sp6cu",
                "https://animehindiworld.seekplays.com/#8c3xl",
                "https://animehindiworld.seekplays.com/#5aslc",
                "https://animehindiworld.seekplays.com/#iut5q",
                "https://animehindiworld.seekplays.com/#xhird",
                "https://animehindiworld.seekplays.com/#bwe9c",
                "https://animehindiworld.seekplays.com/#ltcks",
                "https://animehindiworld.seekplays.com/#kshxz",
                "https://animehindiworld.seekplays.com/#wqfeo",
                "https://animehindiworld.seekplays.com/#39aiv",
                "https://animehindiworld.seekplays.com/#o1njh"
            ],
            "server2": []
        },
        {
            "name": "Season 4",
            "server1": [
                "https://animehindiworld.seekplays.com/#tjp5p",
                "https://animehindiworld.seekplays.com/#xh3yy",
                "https://animehindiworld.seekplays.com/#1xdg5",
                "https://animehindiworld.seekplays.com/#6mec8",
                "https://animehindiworld.seekplays.com/#mzfbn",
                "https://animehindiworld.seekplays.com/#9eg39",
                "https://animehindiworld.seekplays.com/#ksczn",
                "https://animehindiworld.seekplays.com/#gy19w",
                "https://animehindiworld.seekplays.com/#ugoit",
                "https://animehindiworld.seekplays.com/#bwmsl",
                "https://animehindiworld.seekplays.com/#8chft",
                "https://animehindiworld.seekplays.com/#wqzp9",
                "https://animehindiworld.seekplays.com/#ltszk",
                "https://animehindiworld.seekplays.com/#h698n",
                "https://animehindiworld.seekplays.com/#spblk",
                "https://animehindiworld.seekplays.com/#aojib",
                "https://animehindiworld.seekplays.com/#vdrod",
                "https://animehindiworld.seekplays.com/#jvnak",
                "https://animehindiworld.seekplays.com/#o1vu8",
                "https://animehindiworld.seekplays.com/#iuadn",
                "https://animehindiworld.seekplays.com/#iuadb",
                "https://animehindiworld.seekplays.com/#cb6kx",
                "https://animehindiworld.seekplays.com/#nrqji",
                "https://animehindiworld.seekplays.com/#efy6b",
                "https://animehindiworld.seekplays.com/#5atru",
                "https://animehindiworld.seekplays.com/#39uxo",
                "https://animehindiworld.seekplays.com/#pnwtm"
            ],
            "server2": []
        },
        {
            "name": "Season 5",
            "server1": [
                "https://animehindiworld.seekplays.com/#9egug",
                "https://animehindiworld.seekplays.com/#o1vb5",
                "https://animehindiworld.seekplays.com/#bwm9h",
                "https://animehindiworld.seekplays.com/#h695n",
                "https://animehindiworld.seekplays.com/#kscdy",
                "https://animehindiworld.seekplays.com/#cb635",
                "https://animehindiworld.seekplays.com/#wqzgp",
                "https://animehindiworld.seekplays.com/#aojte",
                "https://animehindiworld.seekplays.com/#ugoap",
                "https://animehindiworld.seekplays.com/#h695y",
                "https://animehindiworld.seekplays.com/#mzfgf",
                "https://animehindiworld.seekplays.com/#1xdwh",
                "https://animehindiworld.seekplays.com/#bwmu3",
                "https://animehindiworld.seekplays.com/#6mea5",
                "https://animehindiworld.seekplays.com/#iuaky",
                "https://animehindiworld.seekplays.com/#h69iv",
                "https://animehindiworld.seekplays.com/#39ulm",
                "https://animehindiworld.seekplays.com/#5atlh",
                "https://animehindiworld.seekplays.com/#8chrx",
                "https://animehindiworld.seekplays.com/#ltskc",
                "https://animehindiworld.seekplays.com/#gy1of",
                "https://animehindiworld.seekplays.com/#jvnb3",
                "https://animehindiworld.seekplays.com/#5atkp",
                "https://animehindiworld.seekplays.com/#spb3i",
                "https://animehindiworld.seekplays.com/#kscdf",
                "https://animehindiworld.seekplays.com/#jvn6i",
                "https://animehindiworld.seekplays.com/#spbca",
                "https://animehindiworld.seekplays.com/#nrqec",
                "https://animehindiworld.seekplays.com/#kscxf"
            ],
            "server2": []
        },
        {
            "name": "Season 6",
            "server1": [
                "https://animehindiworld.seekplays.com/#cb9zf",
                "https://animehindiworld.seekplays.com/#39ay9",
                "https://animehindiworld.seekplays.com/#5asvq",
                "https://animehindiworld.seekplays.com/#1xr9d",
                "https://animehindiworld.seekplays.com/#gyvhj",
                "https://animehindiworld.seekplays.com/#nrzax",
                "https://animehindiworld.seekplays.com/#8c3mv",
                "https://animehindiworld.seekplays.com/#tjbqt",
                "https://animehindiworld.seekplays.com/#sp6qq",
                "https://animehindiworld.seekplays.com/#ef1ct",
                "https://animehindiworld.seekplays.com/#o1n3z",
                "https://animehindiworld.seekplays.com/#9eo8s",
                "https://animehindiworld.seekplays.com/#jvwiq",
                "https://animehindiworld.seekplays.com/#8c3mi",
                "https://animehindiworld.seekplays.com/#ugjx3",
                "https://animehindiworld.seekplays.com/#6mgkz",
                "https://animehindiworld.seekplays.com/#kshwg",
                "https://animehindiworld.seekplays.com/#iut1o",
                "https://animehindiworld.seekplays.com/#wqftc",
                "https://animehindiworld.seekplays.com/#xhiem",
                "https://animehindiworld.seekplays.com/#sp6q8",
                "https://animehindiworld.seekplays.com/#h6ufo",
                "https://animehindiworld.seekplays.com/#mzyso",
                "https://animehindiworld.seekplays.com/#h6ufb",
                "https://animehindiworld.seekplays.com/#kshwo"
            ],
            "server2": []
        },
        {
            "name": "Season 7",
            "server1": [
                "https://animehindiworld.seekplays.com/#o1vj3",
                "https://animehindiworld.seekplays.com/#8ch8l",
                "https://animehindiworld.seekplays.com/#efyge",
                "https://animehindiworld.seekplays.com/#tjpsm",
                "https://animehindiworld.seekplays.com/#6me93",
                "https://animehindiworld.seekplays.com/#vdrn5",
                "https://animehindiworld.seekplays.com/#ugouj",
                "https://animehindiworld.seekplays.com/#nrqwt",
                "https://animehindiworld.seekplays.com/#h693z",
                "https://animehindiworld.seekplays.com/#ltsls",
                "https://animehindiworld.seekplays.com/#wqzmo",
                "https://animehindiworld.seekplays.com/#5at5c",
                "https://animehindiworld.seekplays.com/#h6931",
                "https://animehindiworld.seekplays.com/#5atlj",
                "https://animehindiworld.seekplays.com/#ksc8q",
                "https://animehindiworld.seekplays.com/#xh3dd",
                "https://animehindiworld.seekplays.com/#ksc8z",
                "https://animehindiworld.seekplays.com/#iua5e",
                "https://animehindiworld.seekplays.com/#jvnph",
                "https://animehindiworld.seekplays.com/#spbch",
                "https://animehindiworld.seekplays.com/#39uin",
                "https://animehindiworld.seekplays.com/#iua5z",
                "https://animehindiworld.seekplays.com/#cb6hi",
                "https://animehindiworld.seekplays.com/#bwm6c",
                "https://animehindiworld.seekplays.com/#1xdvs",
                "https://animehindiworld.seekplays.com/#spbsu"
            ],
            "server2": []
        },
        {
            "name": "Season 8",
            "server1": [
                "https://animehindiworld.seekplays.com/#h69hq",
                "https://animehindiworld.seekplays.com/#h69hy",
                "https://animehindiworld.seekplays.com/#8ccl5",
                "https://animehindiworld.seekplays.com/#nrqna",
                "https://animehindiworld.seekplays.com/#39u3v",
                "https://animehindiworld.seekplays.com/#ksckr",
                "https://animehindiworld.seekplays.com/#sppa9",
                "https://animehindiworld.seekplays.com/#xh3xx",
                "https://animehindiworld.seekplays.com/#8ch8p",
                "https://animehindiworld.seekplays.com/#bwmbs",
                "https://animehindiworld.seekplays.com/#aojam",
                "https://animehindiworld.seekplays.com/#iuaim",
                "https://animehindiworld.seekplays.com/#9eg9e",
                "https://animehindiworld.seekplays.com/#effww",
                "https://animehindiworld.seekplays.com/#tjptw",
                "https://animehindiworld.seekplays.com/#o1voh",
                "https://animehindiworld.seekplays.com/#wqzwg",
                "https://animehindiworld.seekplays.com/#vdrvi",
                "https://animehindiworld.seekplays.com/#spbsc",
                "https://animehindiworld.seekplays.com/#gy1gz",
                "https://animehindiworld.seekplays.com/#6me6h",
                "https://animehindiworld.seekplays.com/#5at5o",
                "https://animehindiworld.seekplays.com/#ksckq",
                "https://animehindiworld.seekplays.com/#1xd1t",
                "https://animehindiworld.seekplays.com/#jvnjc",
                "https://animehindiworld.seekplays.com/#cb6c3"
            ],
            "server2": []
        },
        {
            "name": "Season 9",
            "server1": [
                "https://animehindiworld.seekplays.com/#ugg6o",
                "https://animehindiworld.seekplays.com/#mzznr",
                "https://animehindiworld.seekplays.com/#vddy3",
                "https://animehindiworld.seekplays.com/#pnnoz",
                "https://animehindiworld.seekplays.com/#aoo9w",
                "https://animehindiworld.seekplays.com/#9eebm",
                "https://animehindiworld.seekplays.com/#gyymq",
                "https://animehindiworld.seekplays.com/#5aa3s"
            ],
            "server2": []
        }
    ]
},
{
    "id": "naruto-shippuden",
    "title": "Naruto Shippuden",
    "poster": "https://image.tmdb.org/t/p/w92/placeholder.jpg",
    "year": "2007",
    "duration": "24m",
    "rating": "8.7",
    "genres": "Action, Adventure, Fantasy",
    "description": "Naruto Uzumaki is back! After training for two and a half years with Jiraiya, he returns to the Hidden Leaf Village to continue his quest to become Hokage and save his friend Sasuke.",
    "seasons": [
        {
            "name": "Season 1",
            "server1": [
                "https://animehindiworld.seekplays.com/#pnvae",
                "https://animehindiworld.seekplays.com/#cbpkr",
                "https://animehindiworld.seekplays.com/#kstqn",
                "https://animehindiworld.seekplays.com/#spj5i",
                "https://animehindiworld.seekplays.com/#wqrju",
                "https://animehindiworld.seekplays.com/#efzb6",
                "https://animehindiworld.seekplays.com/#9emhu",
                "https://animehindiworld.seekplays.com/#mzqjn",
                "https://animehindiworld.seekplays.com/#cbpld",
                "https://animehindiworld.seekplays.com/#spjlx",
                "https://animehindiworld.seekplays.com/#h6bkw",
                "https://animehindiworld.seekplays.com/#xhcyv",
                "https://animehindiworld.seekplays.com/#efz69",
                "https://animehindiworld.seekplays.com/#vdxgr",
                "https://animehindiworld.seekplays.com/#jv1u8",
                "https://animehindiworld.seekplays.com/#6mwsx",
                "https://animehindiworld.seekplays.com/#396xp",
                "https://animehindiworld.seekplays.com/#uge3s",
                "https://animehindiworld.seekplays.com/#ltark",
                "https://animehindiworld.seekplays.com/#h6bkg"
            ],
            "server2": []
        },
        {
            "name": "Season 2",
            "server1": [
                "https://animehindiworld.seekplays.com/#o1y9x",
                "https://animehindiworld.seekplays.com/#bwns8",
                "https://animehindiworld.seekplays.com/#wqrpa",
                "https://animehindiworld.seekplays.com/#bwntk",
                "https://animehindiworld.seekplays.com/#xhcf1",
                "https://animehindiworld.seekplays.com/#8csff",
                "https://animehindiworld.seekplays.com/#ugeht",
                "https://animehindiworld.seekplays.com/#aog36",
                "https://animehindiworld.seekplays.com/#iu9x6",
                "https://animehindiworld.seekplays.com/#3968j",
                "https://animehindiworld.seekplays.com/#iu9d9",
                "https://animehindiworld.seekplays.com/#mzqbm",
                "https://animehindiworld.seekplays.com/#bwnu5",
                "https://animehindiworld.seekplays.com/#wqro9",
                "https://animehindiworld.seekplays.com/#cbp5x",
                "https://animehindiworld.seekplays.com/#efzpb",
                "https://animehindiworld.seekplays.com/#9emtb",
                "https://animehindiworld.seekplays.com/#396lg",
                "https://animehindiworld.seekplays.com/#o1ybk",
                "https://animehindiworld.seekplays.com/#ugeca",
                "https://animehindiworld.seekplays.com/#h6b5v",
                "https://animehindiworld.seekplays.com/#6mwak",
                "https://animehindiworld.seekplays.com/#wqrg6",
                "https://animehindiworld.seekplays.com/#8csra",
                "https://animehindiworld.seekplays.com/#vdxmx",
                "https://animehindiworld.seekplays.com/#aogcp",
                "https://animehindiworld.seekplays.com/#xhczy",
                "https://animehindiworld.seekplays.com/#spj3l",
                "https://animehindiworld.seekplays.com/#1x8wi",
                "https://animehindiworld.seekplays.com/#xhcqf",
                "https://animehindiworld.seekplays.com/#kstd1",
                "https://animehindiworld.seekplays.com/#5auxk",
                "https://animehindiworld.seekplays.com/#8csqq"
            ],
            "server2": []
        },
        {
            "name": "Season 3",
            "server1": [
                "https://animehindiworld.seekplays.com/#cbp3k",
                "https://animehindiworld.seekplays.com/#8csx9",
                "https://animehindiworld.seekplays.com/#ltak3",
                "https://animehindiworld.seekplays.com/#pnvbv",
                "https://animehindiworld.seekplays.com/#5aulb",
                "https://animehindiworld.seekplays.com/#iu95o",
                "https://animehindiworld.seekplays.com/#efzoj",
                "https://animehindiworld.seekplays.com/#h6b3y",
                "https://animehindiworld.seekplays.com/#jv1pi",
                "https://animehindiworld.seekplays.com/#h6b3n",
                "https://animehindiworld.seekplays.com/#o1yj5",
                "https://animehindiworld.seekplays.com/#396im",
                "https://animehindiworld.seekplays.com/#spjhc",
                "https://animehindiworld.seekplays.com/#tjosg",
                "https://animehindiworld.seekplays.com/#vdxnk",
                "https://animehindiworld.seekplays.com/#aogto",
                "https://animehindiworld.seekplays.com/#gyfo1",
                "https://animehindiworld.seekplays.com/#5auk5"
            ],
            "server2": []
        },
        {
            "name": "Season 4",
            "server1": [
                "https://animehindiworld.seekplays.com/#3963w",
                "https://animehindiworld.seekplays.com/#mzqmf",
                "https://animehindiworld.seekplays.com/#pnvp1",
                "https://animehindiworld.seekplays.com/#1x81c",
                "https://animehindiworld.seekplays.com/#gyfgy",
                "https://animehindiworld.seekplays.com/#5au5p",
                "https://animehindiworld.seekplays.com/#efzgo",
                "https://animehindiworld.seekplays.com/#vdxvl",
                "https://animehindiworld.seekplays.com/#aogag",
                "https://animehindiworld.seekplays.com/#nrdns",
                "https://animehindiworld.seekplays.com/#8csxx",
                "https://animehindiworld.seekplays.com/#9em9o",
                "https://animehindiworld.seekplays.com/#5au53",
                "https://animehindiworld.seekplays.com/#ugeub",
                "https://animehindiworld.seekplays.com/#tjote",
                "https://animehindiworld.seekplays.com/#xhcdq",
                "https://animehindiworld.seekplays.com/#iu9ig"
            ],
            "server2": []
        },
        {
            "name": "Season 5",
            "server1": [
                "https://animehindiworld.seekplays.com/#9ewk3",
                "https://animehindiworld.seekplays.com/#bwv5f",
                "https://animehindiworld.seekplays.com/#h6pq9",
                "https://animehindiworld.seekplays.com/#iu6yb",
                "https://animehindiworld.seekplays.com/#spory",
                "https://animehindiworld.seekplays.com/#wqdai",
                "https://animehindiworld.seekplays.com/#8ctnl",
                "https://animehindiworld.seekplays.com/#gyzc6",
                "https://animehindiworld.seekplays.com/#1xkbq",
                "https://animehindiworld.seekplays.com/#ksanb",
                "https://animehindiworld.seekplays.com/#cbjqv",
                "https://animehindiworld.seekplays.com/#pn1i9",
                "https://animehindiworld.seekplays.com/#vd89n",
                "https://animehindiworld.seekplays.com/#xhsmo",
                "https://animehindiworld.seekplays.com/#8ctwm",
                "https://animehindiworld.seekplays.com/#39bza",
                "https://animehindiworld.seekplays.com/#aoexh",
                "https://animehindiworld.seekplays.com/#ugm8l",
                "https://animehindiworld.seekplays.com/#5a91y",
                "https://animehindiworld.seekplays.com/#5a915",
                "https://animehindiworld.seekplays.com/#ksanp",
                "https://animehindiworld.seekplays.com/#mzrtb",
                "https://animehindiworld.seekplays.com/#6mnl1",
                "https://animehindiworld.seekplays.com/#iu6fc"
            ],
            "server2": []
        },
        {
            "name": "Season 6",
            "server1": [
                "https://animehindiworld.seekplays.com/#5a9f3",
                "https://animehindiworld.seekplays.com/#spoxz",
                "https://animehindiworld.seekplays.com/#vd86v",
                "https://animehindiworld.seekplays.com/#1xkpr",
                "https://animehindiworld.seekplays.com/#efqtc",
                "https://animehindiworld.seekplays.com/#6mnif",
                "https://animehindiworld.seekplays.com/#xhsne",
                "https://animehindiworld.seekplays.com/#8ctv5",
                "https://animehindiworld.seekplays.com/#xhswg",
                "https://animehindiworld.seekplays.com/#39bqu",
                "https://animehindiworld.seekplays.com/#h6pr6",
                "https://animehindiworld.seekplays.com/#cbjr1",
                "https://animehindiworld.seekplays.com/#pn136",
                "https://animehindiworld.seekplays.com/#cbjdy",
                "https://animehindiworld.seekplays.com/#ksa1o",
                "https://animehindiworld.seekplays.com/#jvycz",
                "https://animehindiworld.seekplays.com/#o1fsf",
                "https://animehindiworld.seekplays.com/#spodd",
                "https://animehindiworld.seekplays.com/#9ewlh",
                "https://animehindiworld.seekplays.com/#nrx6d",
                "https://animehindiworld.seekplays.com/#iu6zs",
                "https://animehindiworld.seekplays.com/#ksa1j",
                "https://animehindiworld.seekplays.com/#wqd9h",
                "https://animehindiworld.seekplays.com/#5a9yf",
                "https://animehindiworld.seekplays.com/#ugmk5",
                "https://animehindiworld.seekplays.com/#tjgxs",
                "https://animehindiworld.seekplays.com/#spodf",
                "https://animehindiworld.seekplays.com/#gyzsb",
                "https://animehindiworld.seekplays.com/#8ctnw",
                "https://animehindiworld.seekplays.com/#efqas",
                "https://animehindiworld.seekplays.com/#h6prj"
            ],
            "server2": []
        },
{
  
      
            "name": "Season 7",
            "server1": [
                "https://animehindiworld.seekplays.com/#vdkyl",
                "https://animehindiworld.seekplays.com/#8cal6",
                "https://animehindiworld.seekplays.com/#mzdnf",
                "https://animehindiworld.seekplays.com/#aom9g",
                "https://animehindiworld.seekplays.com/#tjeue",
                "https://animehindiworld.seekplays.com/#iubhg",
                "https://animehindiworld.seekplays.com/#5a63p",
                "https://animehindiworld.seekplays.com/#ugw6b"
            ],
            "server2": []
        },
        {
            "name": "Season 8",
            "server1": [
                "https://animehindiworld.seekplays.com/#mzdyr",
                "https://animehindiworld.seekplays.com/#mzdfd",
                "https://animehindiworld.seekplays.com/#jvfws",
                "https://animehindiworld.seekplays.com/#39pa1",
                "https://animehindiworld.seekplays.com/#iuban",
                "https://animehindiworld.seekplays.com/#8cac3",
                "https://animehindiworld.seekplays.com/#ksucd",
                "https://animehindiworld.seekplays.com/#gyq1r",
                "https://animehindiworld.seekplays.com/#spgpa",
                "https://animehindiworld.seekplays.com/#lt9ct",
                "https://animehindiworld.seekplays.com/#h6j9d",
                "https://animehindiworld.seekplays.com/#vdkrh",
                "https://animehindiworld.seekplays.com/#efryn",
                "https://animehindiworld.seekplays.com/#ksuhd",
                "https://animehindiworld.seekplays.com/#39puy",
                "https://animehindiworld.seekplays.com/#aompw",
                "https://animehindiworld.seekplays.com/#1xlx9",
                "https://animehindiworld.seekplays.com/#lt9sa",
                "https://animehindiworld.seekplays.com/#wqxqw",
                "https://animehindiworld.seekplays.com/#9engw",
                "https://animehindiworld.seekplays.com/#ugwog",
                "https://animehindiworld.seekplays.com/#tjebn",
                "https://animehindiworld.seekplays.com/#bw1wu",
                "https://animehindiworld.seekplays.com/#aomjn"
            ],
            "server2": []
        },
        {
            "name": "Season 9",
            "server1": [
                "https://animehindiworld.seekplays.com/#gyqwf",
                "https://animehindiworld.seekplays.com/#8ca5b",
                "https://animehindiworld.seekplays.com/#9enpg",
                "https://animehindiworld.seekplays.com/#5a6hj",
                "https://animehindiworld.seekplays.com/#ksu5z",
                "https://animehindiworld.seekplays.com/#mzdvz",
                "https://animehindiworld.seekplays.com/#lt93c",
                "https://animehindiworld.seekplays.com/#ksu5f",
                "https://animehindiworld.seekplays.com/#1xlzs",
                "https://animehindiworld.seekplays.com/#pnygy",
                "https://animehindiworld.seekplays.com/#spgua",
                "https://animehindiworld.seekplays.com/#wqxvj",
                "https://animehindiworld.seekplays.com/#5a6hh",
                "https://animehindiworld.seekplays.com/#39psn",
                "https://animehindiworld.seekplays.com/#tje9m",
                "https://animehindiworld.seekplays.com/#ugwbp",
                "https://animehindiworld.seekplays.com/#vdkf5",
                "https://animehindiworld.seekplays.com/#h6jt1",
                "https://animehindiworld.seekplays.com/#nr8yt",
                "https://animehindiworld.seekplays.com/#8cal8",
                "https://animehindiworld.seekplays.com/#spga3"
            ],
            "server2": []
        },
        {
            "name": "Season 10",
            "server1": [
                "https://animehindiworld.seekplays.com/#5a6sg",
                "https://animehindiworld.seekplays.com/#iubtr",
                "https://animehindiworld.seekplays.com/#1xlra",
                "https://animehindiworld.seekplays.com/#o1znc",
                "https://animehindiworld.seekplays.com/#8ca3j",
                "https://animehindiworld.seekplays.com/#9enom",
                "https://animehindiworld.seekplays.com/#h6juf",
                "https://animehindiworld.seekplays.com/#pnymz",
                "https://animehindiworld.seekplays.com/#iubtw",
                "https://animehindiworld.seekplays.com/#bw1et",
                "https://animehindiworld.seekplays.com/#ksuhr",
                "https://animehindiworld.seekplays.com/#h6jur",
                "https://animehindiworld.seekplays.com/#5a6tt",
                "https://animehindiworld.seekplays.com/#spgb6",
                "https://animehindiworld.seekplays.com/#wqxfe",
                "https://animehindiworld.seekplays.com/#cbo9h",
                "https://animehindiworld.seekplays.com/#nr8zu",
                "https://animehindiworld.seekplays.com/#5a6ss",
                "https://animehindiworld.seekplays.com/#vdkq3",
                "https://animehindiworld.seekplays.com/#xht3k",
                "https://animehindiworld.seekplays.com/#6mvgc",
                "https://animehindiworld.seekplays.com/#spg6s",
                "https://animehindiworld.seekplays.com/#8cahi",
                "https://animehindiworld.seekplays.com/#ugwjo",
                "https://animehindiworld.seekplays.com/#gyqvq"
            ],
            "server2": []
        },
        {
            "name": "Season 11",
            "server1": [
                "https://animehindiworld.seekplays.com/#tjepv",
                "https://animehindiworld.seekplays.com/#6mves",
                "https://animehindiworld.seekplays.com/#1xldu",
                "https://animehindiworld.seekplays.com/#pnywq",
                "https://animehindiworld.seekplays.com/#lt9a9",
                "https://animehindiworld.seekplays.com/#xhthl",
                "https://animehindiworld.seekplays.com/#spgju",
                "https://animehindiworld.seekplays.com/#wqxzm",
                "https://animehindiworld.seekplays.com/#8cash",
                "https://animehindiworld.seekplays.com/#jvfnt",
                "https://animehindiworld.seekplays.com/#aomov",
                "https://animehindiworld.seekplays.com/#h6j9z",
                "https://animehindiworld.seekplays.com/#ugwge",
                "https://animehindiworld.seekplays.com/#h6j6q",
                "https://animehindiworld.seekplays.com/#mzdq8",
                "https://animehindiworld.seekplays.com/#spgjp",
                "https://animehindiworld.seekplays.com/#9enmv",
                "https://animehindiworld.seekplays.com/#5a6uu",
                "https://animehindiworld.seekplays.com/#5a6te",
                "https://animehindiworld.seekplays.com/#o1zvs",
                "https://animehindiworld.seekplays.com/#ksus8"
            ],
            "server2": []
        },
        {
            "name": "Season 12",
            "server1": [
                "https://animehindiworld.seekplays.com/#5a6aa",
                "https://animehindiworld.seekplays.com/#efrz1",
                "https://animehindiworld.seekplays.com/#nr8q9",
                "https://animehindiworld.seekplays.com/#bw1ma",
                "https://animehindiworld.seekplays.com/#6mvmt",
                "https://animehindiworld.seekplays.com/#gyqyd",
                "https://animehindiworld.seekplays.com/#ksucx",
                "https://animehindiworld.seekplays.com/#cbo6c",
                "https://animehindiworld.seekplays.com/#iubad",
                "https://animehindiworld.seekplays.com/#cbopt",
                "https://animehindiworld.seekplays.com/#efrfv",
                "https://animehindiworld.seekplays.com/#9enen",
                "https://animehindiworld.seekplays.com/#xhtc5",
                "https://animehindiworld.seekplays.com/#h6j6x",
                "https://animehindiworld.seekplays.com/#ksusx",
                "https://animehindiworld.seekplays.com/#8cacg",
                "https://animehindiworld.seekplays.com/#efrqy",
                "https://animehindiworld.seekplays.com/#tjeoy",
                "https://animehindiworld.seekplays.com/#xhtsi",
                "https://animehindiworld.seekplays.com/#39p6z",
                "https://animehindiworld.seekplays.com/#o1zya",
                "https://animehindiworld.seekplays.com/#1xl86",
                "https://animehindiworld.seekplays.com/#jvf1u",
                "https://animehindiworld.seekplays.com/#vdkxs",
                "https://animehindiworld.seekplays.com/#5a6uw",
                "https://animehindiworld.seekplays.com/#pnyvd",
                "https://animehindiworld.seekplays.com/#8case",
                "https://animehindiworld.seekplays.com/#ksutk",
                "https://animehindiworld.seekplays.com/#cboja",
                "https://animehindiworld.seekplays.com/#h6jbr",
                "https://animehindiworld.seekplays.com/#wqxdv",
                "https://animehindiworld.seekplays.com/#spgoj",
                "https://animehindiworld.seekplays.com/#gyqfx"
            ],
            "server2": []
        },
        {
            "name": "Season 13",
            "server1": [
                "https://animehindiworld.seekplays.com/#tjegf",
                "https://animehindiworld.seekplays.com/#9enw1",
                "https://animehindiworld.seekplays.com/#8catc",
                "https://animehindiworld.seekplays.com/#5a699",
                "https://animehindiworld.seekplays.com/#spgo9",
                "https://animehindiworld.seekplays.com/#gyqz8",
                "https://animehindiworld.seekplays.com/#o1zfu",
                "https://animehindiworld.seekplays.com/#iub91",
                "https://animehindiworld.seekplays.com/#ksut8",
                "https://animehindiworld.seekplays.com/#h6jpk",
                "https://animehindiworld.seekplays.com/#39pbq",
                "https://animehindiworld.seekplays.com/#vdk8t",
                "https://animehindiworld.seekplays.com/#nr8db",
                "https://animehindiworld.seekplays.com/#bw1n9",
                "https://animehindiworld.seekplays.com/#ugwmw",
                "https://animehindiworld.seekplays.com/#wqxx1",
                "https://animehindiworld.seekplays.com/#iub98",
                "https://animehindiworld.seekplays.com/#h6jb8",
                "https://animehindiworld.seekplays.com/#xhtt3",
                "https://animehindiworld.seekplays.com/#bw1v6"
            ],
            "server2": []
        },
        {
            "name": "Season 14",
            "server1": [
                "https://animehindiworld.seekplays.com/#o1zz9",
                "https://animehindiworld.seekplays.com/#gyqqk",
                "https://animehindiworld.seekplays.com/#1xlkb",
                "https://animehindiworld.seekplays.com/#spggo",
                "https://animehindiworld.seekplays.com/#h6jpd",
                "https://animehindiworld.seekplays.com/#efrrf",
                "https://animehindiworld.seekplays.com/#lt99b",
                "https://animehindiworld.seekplays.com/#tjeez",
                "https://animehindiworld.seekplays.com/#iub6k",
                "https://animehindiworld.seekplays.com/#iub6y",
                "https://animehindiworld.seekplays.com/#pny1x",
                "https://animehindiworld.seekplays.com/#h6jjx",
                "https://animehindiworld.seekplays.com/#9enny",
                "https://animehindiworld.seekplays.com/#8caaw",
                "https://animehindiworld.seekplays.com/#vdkka",
                "https://animehindiworld.seekplays.com/#ksuu5",
                "https://animehindiworld.seekplays.com/#8caas",
                "https://animehindiworld.seekplays.com/#spgg6",
                "https://animehindiworld.seekplays.com/#5a69n",
                "https://animehindiworld.seekplays.com/#ugwwn",
                "https://animehindiworld.seekplays.com/#iubbf",
                "https://animehindiworld.seekplays.com/#39ppr",
                "https://animehindiworld.seekplays.com/#mzddl",
                "https://animehindiworld.seekplays.com/#pnyy8",
                "https://animehindiworld.seekplays.com/#ksuak"
            ],
            "server2": []
        },
        {
            "name": "Season 15",
            "server1": [
                "https://animehindiworld.seekplays.com/#5a6bb",
                "https://animehindiworld.seekplays.com/#1xllp",
                "https://animehindiworld.seekplays.com/#h6jjl",
                "https://animehindiworld.seekplays.com/#lt96p",
                "https://animehindiworld.seekplays.com/#8caun",
                "https://animehindiworld.seekplays.com/#cbog9",
                "https://animehindiworld.seekplays.com/#efrdz",
                "https://animehindiworld.seekplays.com/#nr8ko",
                "https://animehindiworld.seekplays.com/#jvff6",
                "https://animehindiworld.seekplays.com/#ugwnv",
                "https://animehindiworld.seekplays.com/#aomwz",
                "https://animehindiworld.seekplays.com/#nr88j",
                "https://animehindiworld.seekplays.com/#8caut",
                "https://animehindiworld.seekplays.com/#pnyfk",
                "https://animehindiworld.seekplays.com/#iubbl",
                "https://animehindiworld.seekplays.com/#vdklu",
                "https://animehindiworld.seekplays.com/#39pjd",
                "https://animehindiworld.seekplays.com/#ksu95",
                "https://animehindiworld.seekplays.com/#iubpz",
                "https://animehindiworld.seekplays.com/#wqx8y",
                "https://animehindiworld.seekplays.com/#6mvv9",
                "https://animehindiworld.seekplays.com/#bw11b",
                "https://animehindiworld.seekplays.com/#1xl5j",
                "https://animehindiworld.seekplays.com/#spgeb",
                "https://animehindiworld.seekplays.com/#spgeg",
                "https://animehindiworld.seekplays.com/#h6jo8",
                "https://animehindiworld.seekplays.com/#mzdx5",
                "https://animehindiworld.seekplays.com/#5a66v"
            ],
            "server2": []
        },
        {
            "name": "Season 16",
            "server1": [
                "https://animehindiworld.seekplays.com/#spgme",
                "https://animehindiworld.seekplays.com/#ksu63",
                "https://animehindiworld.seekplays.com/#9en1z",
                "https://animehindiworld.seekplays.com/#8ca9a",
                "https://animehindiworld.seekplays.com/#cboe6",
                "https://animehindiworld.seekplays.com/#pnyzl",
                "https://animehindiworld.seekplays.com/#5a6pp",
                "https://animehindiworld.seekplays.com/#lt9bj",
                "https://animehindiworld.seekplays.com/#aomnq",
                "https://animehindiworld.seekplays.com/#vdk59",
                "https://animehindiworld.seekplays.com/#efrxq",
                "https://animehindiworld.seekplays.com/#tjewr"
            ],
            "server2": []
        }
    ]

   
},
{
    "id": "kaguya-sama-love-is-war",
    "title": "Kaguya-sama: Love Is War",
    "poster": "https://image.tmdb.org/t/p/w92/placeholder.jpg",
    "year": "2019",
    "duration": "24m",
    "rating": "8.5",
    "genres": "Comedy, Romance, Psychological",
    "description": "Two genius students, Miyuki Shirogane and Kaguya Shinomiya, are in love with each other but are too proud to confess it first, leading to a series of psychological battles to make the other person confess.",
    "seasons": [
        {
            "name": "Season 1",
            "server1": [
                "https://animehindiworld.seekplays.com/#h6by6",
                "https://animehindiworld.seekplays.com/#h6bya",
                "https://animehindiworld.seekplays.com/#nrdtz",
                "https://animehindiworld.seekplays.com/#cbpfn",
                "https://animehindiworld.seekplays.com/#kstmb",
                "https://animehindiworld.seekplays.com/#6mw8v",
                "https://animehindiworld.seekplays.com/#bwnky",
                "https://animehindiworld.seekplays.com/#o1yiv",
                "https://animehindiworld.seekplays.com/#1x8uf",
                "https://animehindiworld.seekplays.com/#wqrs5",
                "https://animehindiworld.seekplays.com/#iu9v6",
                "https://animehindiworld.seekplays.com/#kstm6"
            ],
            "server2": []
        }
    ]
},
{
    "id": "kaiju-no-8",
    "title": "Kaiju No. 8",
    "poster": "https://image.tmdb.org/t/p/w92/placeholder.jpg",
    "year": "2024",
    "duration": "24m",
    "rating": "8.4",
    "genres": "Action, Sci-Fi, Animation",
    "description": "In a world plagued by creatures known as Kaiju, Kafka Hibino aspires to enlist in the Japan Defense Force to defeat them. After a small Kaiju enters his body, he gains the ability to transform into one himself.",
    "seasons": [
        {
            "name": "Season 1",
            "server1": [
                "https://animehindiworld.seekplays.com/#bwn81",
                "https://animehindiworld.seekplays.com/#xhcop",
                "https://animehindiworld.seekplays.com/#spjfz",
                "https://animehindiworld.seekplays.com/#8csgg",
                "https://animehindiworld.seekplays.com/#9emd5",
                "https://animehindiworld.seekplays.com/#cbpyw",
                "https://animehindiworld.seekplays.com/#5auwv",
                "https://animehindiworld.seekplays.com/#kste9",
                "https://animehindiworld.seekplays.com/#wqrcl",
                "https://animehindiworld.seekplays.com/#uger8",
                "https://animehindiworld.seekplays.com/#spjfv",
                "https://animehindiworld.seekplays.com/#efz3i"
            ],
            "server2": []
        },
        {
            "name": "Season 2",
            "server1": [
                "https://animehindiworld.seekplays.com/#9emxi",
                "https://animehindiworld.seekplays.com/#vdxaw",
                "https://animehindiworld.seekplays.com/#pnvlu",
                "https://animehindiworld.seekplays.com/#1x89z",
                "https://animehindiworld.seekplays.com/#5aunl",
                "https://animehindiworld.seekplays.com/#396yt",
                "https://animehindiworld.seekplays.com/#ltawy",
                "https://animehindiworld.seekplays.com/#mzqc6",
                "https://animehindiworld.seekplays.com/#5aun1",
                "https://animehindiworld.seekplays.com/#iu91h",
                "https://animehindiworld.seekplays.com/#aogr3"
            ],
            "server2": []
        }
    ]
},

{
    "id": "demon-slayer",
    "title": "Demon Slayer: Kimetsu no Yaiba",
    "poster": "https://image.tmdb.org/t/p/w92/placeholder.jpg",
    "year": "2019",
    "duration": "24m",
    "rating": "8.7",
    "genres": "Action, Adventure, Fantasy",
    "description": "After his family is brutally murdered and his sister turned into a demon, Tanjiro Kamado sets out to become a demon slayer to find a cure and get revenge.",
    "seasons": [
        {
            "name": "Season 1",
            "server1": [
                "https://animehindiworld.seekplays.com/#6mwiz",
                "https://animehindiworld.seekplays.com/#9em5s",
                "https://animehindiworld.seekplays.com/#wqr9c",
                "https://animehindiworld.seekplays.com/#ltayr",
                "https://animehindiworld.seekplays.com/#h6bro",
                "https://animehindiworld.seekplays.com/#cbpdf",
                "https://animehindiworld.seekplays.com/#bwn3r",
                "https://animehindiworld.seekplays.com/#vdxpf",
                "https://animehindiworld.seekplays.com/#tjoku",
                "https://animehindiworld.seekplays.com/#nrd6x",
                "https://animehindiworld.seekplays.com/#1x8jx",
                "https://animehindiworld.seekplays.com/#ugel3",
                "https://animehindiworld.seekplays.com/#5auzc",
                "https://animehindiworld.seekplays.com/#8cs13",
                "https://animehindiworld.seekplays.com/#pnvhp",
                "https://animehindiworld.seekplays.com/#mzquo",
                "https://animehindiworld.seekplays.com/#xhcnm",
                "https://animehindiworld.seekplays.com/#396r6",
                "https://animehindiworld.seekplays.com/#5aufq",
                "https://animehindiworld.seekplays.com/#gyftj",
                "https://animehindiworld.seekplays.com/#kst1g",
                "https://animehindiworld.seekplays.com/#396q9",
                "https://animehindiworld.seekplays.com/#8csvi",
                "https://animehindiworld.seekplays.com/#1x8pd",
                "https://animehindiworld.seekplays.com/#h6brb",
                "https://animehindiworld.seekplays.com/#jv1cq"
            ],
            "server2": []
        },
        {
            "name": "Season 2",
            "server1": [
                "https://animehindiworld.seekplays.com/#5auzr",
                "https://animehindiworld.seekplays.com/#ltafd",
                "https://animehindiworld.seekplays.com/#iu9ru",
                "https://animehindiworld.seekplays.com/#spj8k",
                "https://animehindiworld.seekplays.com/#tjol9",
                "https://animehindiworld.seekplays.com/#1x8o8",
                "https://animehindiworld.seekplays.com/#gyfao",
                "https://animehindiworld.seekplays.com/#h6bxj",
                "https://animehindiworld.seekplays.com/#396db",
                "https://animehindiworld.seekplays.com/#xhcvw",
                "https://animehindiworld.seekplays.com/#spj8r",
                "https://animehindiworld.seekplays.com/#8cs11",
                "https://animehindiworld.seekplays.com/#9emit",
                "https://animehindiworld.seekplays.com/#uge5h",
                "https://animehindiworld.seekplays.com/#8csyh",
                "https://animehindiworld.seekplays.com/#cbpxz",
                "https://animehindiworld.seekplays.com/#vdxjz",
                "https://animehindiworld.seekplays.com/#aogla"
            ],
            "server2": []
        },
        {
            "name": "Season 3",
            "server1": [
                "https://animehindiworld.seekplays.com/#tjods",
                "https://animehindiworld.seekplays.com/#9emkh",
                "https://animehindiworld.seekplays.com/#aogxc",
                "https://animehindiworld.seekplays.com/#iu9fs",
                "https://animehindiworld.seekplays.com/#pnvi6",
                "https://animehindiworld.seekplays.com/#8csn5",
                "https://animehindiworld.seekplays.com/#wqra3",
                "https://animehindiworld.seekplays.com/#gyfcb",
                "https://animehindiworld.seekplays.com/#5auy3",
                "https://animehindiworld.seekplays.com/#ltavz",
                "https://animehindiworld.seekplays.com/#5au1f"
            ],
            "server2": []
        },
        {
            "name": "Season 4",
            "server1": [
                "https://animehindiworld.seekplays.com/#iu9fj",
                "https://animehindiworld.seekplays.com/#jv1hz",
                "https://animehindiworld.seekplays.com/#ugeki",
                "https://animehindiworld.seekplays.com/#kstvo",
                "https://animehindiworld.seekplays.com/#spjdx",
                "https://animehindiworld.seekplays.com/#kstvj",
                "https://animehindiworld.seekplays.com/#5auyz",
                "https://animehindiworld.seekplays.com/#lta1q"
            ],
            "server2": []
        }
    ]
}





];
