const animeList = [
    {
        id: "wind-breaker",
        title: "Wind Breaker (Hindi Dub)",
        poster: "https://image.tmdb.org/t/p/w92/8XBaug59lVB45lxo6ZUoghH1Bdj.jpg",
        year: "2024",
        duration: "24m",
        rating: "7.72",
        genres: "Action, Anime, School",
        cast: "Koki Uchiyama, Nobunaga Shimazaki",
        description: "Haruka Sakura wants nothing to do with weaklings—he's only interested in the strongest of the strong. He's just started at Furin High School...",
        seasons: [
            {
                name: "Season 1",
                server1: [
                    "https://vidmoly.net/embed-otx0kv0uyysp.html",
                    "https://vidmoly.net/embed-w3aof5xz648a.html",
                    "https://vidmoly.net/embed-xbla97mxraw2.html",
                    "https://vidmoly.net/embed-7xp0m9w2mdkl.html",
                    "https://vidmoly.net/embed-twu8lb79askx.html",
                    "https://vidmoly.net/embed-sben16btq6f6.html",
                    "https://vidmoly.net/embed-moc619ek69l3.html",
                    "https://vidmoly.net/embed-7izjyy8qzus5.html",
                    "https://vidmoly.net/embed-zzz54lpwl95b.html",
                    "https://vidmoly.net/embed-ifgpim3e87dx.html",
                    "https://vidmoly.net/embed-f95f3jc15soc.html",
                    "https://vidmoly.net/embed-kg3uzhpbusrn.html",
                    "https://vidmoly.net/embed-9zd0zlr2ky26.html"
                ],
                server2: [] // Isme links nahi hain, toh button nahi dikhega
            }
        ]
    },

    {
        id: "solo-leveling",
        title: "Solo Leveling (Hindi Dubbed)",
        poster: "https://image.tmdb.org/t/p/w92/geCRueV3ElhRTr0xtJuEWJt6dJ1.jpg",
        year: "2024",
        duration: "24m",
        rating: "8.7",
        genres: "Action, Adventure, Fantasy",
        cast: "Taito Ban, Reina Ueda",
        description: "In a world where hunters must battle deadly monsters to protect mankind, Sung Jinwoo, a notoriously weak hunter, finds himself in a struggle for survival.",
        seasons: [
            {
                name: "Season 1",
                server1: [
                    "https://animehindiworld.seekplays.com/#kcaxn",
                    "https://animehindiworld.seekplays.com/#ia65p",
                    "https://animehindiworld.seekplays.com/#3ubig",
                    "https://animehindiworld.seekplays.com/#ia65v",
                    "https://animehindiworld.seekplays.com/#wzdm6",
                    "https://animehindiworld.seekplays.com/#5t9ll",
                    "https://animehindiworld.seekplays.com/#ia6ij",
                    "https://animehindiworld.seekplays.com/#kcaky",
                    "https://animehindiworld.seekplays.com/#pwyov",
                    "https://animehindiworld.seekplays.com/#6evp5",
                    "https://animehindiworld.seekplays.com/#8ha56",
                    "https://animehindiworld.seekplays.com/#ajmbe"
                ],
                server2: []
            }
        ]
    },
{
    "id": "haikyuu",
    "title": "Haikyuu!!",
    "poster": "https://image.tmdb.org/t/p/w92/placeholder.jpg",
    "year": "2014",
    "duration": "24m",
    "rating": "8.7",
    "genres": "Animation, Comedy, Drama, Sport",
    "description": "Inspired after watching a volleyball ace nicknamed 'Little Giant' in action, small-statured Shouyou Hinata revives the volleyball club at his middle school. The newly-formed team even makes it to a tournament; however, their first match turns out to be their last when they are brutally squashed by the 'King of the Court,' Tobio Kageyama.",
    "seasons": [
        {
            "name": "Season 1",
            "server1": [
                "https://animehindiworld.seekplays.com/#iuusx",
                "https://animehindiworld.seekplays.com/#bwwgu",
                "https://animehindiworld.seekplays.com/#nrrf6",
                "https://animehindiworld.seekplays.com/#6mmot",
                "https://animehindiworld.seekplays.com/#kss3x",
                "https://animehindiworld.seekplays.com/#cbb9t",
                "https://animehindiworld.seekplays.com/#o11wt",
                "https://animehindiworld.seekplays.com/#kss38",
                "https://animehindiworld.seekplays.com/#jvvma",
                "https://animehindiworld.seekplays.com/#h66ax",
                "https://animehindiworld.seekplays.com/#399tf",
                "https://animehindiworld.seekplays.com/#h66aq",
                "https://animehindiworld.seekplays.com/#wqqyw",
                "https://animehindiworld.seekplays.com/#tjjby",
                "https://animehindiworld.seekplays.com/#spp6p",
                "https://animehindiworld.seekplays.com/#eff11",
                "https://animehindiworld.seekplays.com/#5aasu",
                "https://animehindiworld.seekplays.com/#vddqs",
                "https://animehindiworld.seekplays.com/#lttc9",
                "https://animehindiworld.seekplays.com/#mzzy8",
                "https://animehindiworld.seekplays.com/#gyyvx",
                "https://animehindiworld.seekplays.com/#uggjm",
                "https://animehindiworld.seekplays.com/#aoop1",
                "https://animehindiworld.seekplays.com/#8cc3h",
                "https://animehindiworld.seekplays.com/#xhhi5"
            ],
            "server2": []
        },
        {
            "name": "Season 2",
            "server1": [
                "https://animehindiworld.seekplays.com/#h66ur",
                "https://animehindiworld.seekplays.com/#h66u8",
                "https://animehindiworld.seekplays.com/#sppb9",
                "https://animehindiworld.seekplays.com/#399az",
                "https://animehindiworld.seekplays.com/#iuut8",
                "https://animehindiworld.seekplays.com/#5aasw",
                "https://animehindiworld.seekplays.com/#1xxr6",
                "https://animehindiworld.seekplays.com/#xhh3i",
                "https://animehindiworld.seekplays.com/#o11na",
                "https://animehindiworld.seekplays.com/#nrrzb",
                "https://animehindiworld.seekplays.com/#jvvwu",
                "https://animehindiworld.seekplays.com/#kssh8",
                "https://animehindiworld.seekplays.com/#iuut1",
                "https://animehindiworld.seekplays.com/#gyy18",
                "https://animehindiworld.seekplays.com/#o11vu",
                "https://animehindiworld.seekplays.com/#9eeg1",
                "https://animehindiworld.seekplays.com/#ltts6",
                "https://animehindiworld.seekplays.com/#8cchc",
                "https://animehindiworld.seekplays.com/#uggow",
                "https://animehindiworld.seekplays.com/#399uq",
                "https://animehindiworld.seekplays.com/#h669k",
                "https://animehindiworld.seekplays.com/#iuuak",
                "https://animehindiworld.seekplays.com/#8cchm",
                "https://animehindiworld.seekplays.com/#5aat9",
                "https://animehindiworld.seekplays.com/#sppbj"
            ],
            "server2": []
        }
    ]
},
{
    "id": "naruto",
    "title": "Naruto",
    "poster": "https://image.tmdb.org/t/p/w92/placeholder.jpg",
    "year": "2002",
    "duration": "23m",
    "rating": "8.4",
    "genres": "Action, Adventure, Fantasy",
    "description": "Naruto Uzumaki, a mischievous adolescent ninja, struggles as he searches for recognition and dreams of becoming the Hokage, the village's leader and strongest ninja.",
    "seasons": [
        {
            "name": "Season 1",
            "server1": [
                "https://animehindiworld.seekplays.com/#jvwtk",
                "https://animehindiworld.seekplays.com/#nrzb5",
                "https://animehindiworld.seekplays.com/#ltcfk",
                "https://animehindiworld.seekplays.com/#h6uxe",
                "https://animehindiworld.seekplays.com/#5asqu",
                "https://animehindiworld.seekplays.com/#bwehk",
                "https://animehindiworld.seekplays.com/#8c3yt",
                "https://animehindiworld.seekplays.com/#gyvuw",
                "https://animehindiworld.seekplays.com/#1xro5",
                "https://animehindiworld.seekplays.com/#pnmsm",
                "https://animehindiworld.seekplays.com/#h6udw",
                "https://animehindiworld.seekplays.com/#vdqjd",
                "https://animehindiworld.seekplays.com/#kshfn",
                "https://animehindiworld.seekplays.com/#jvws8",
                "https://animehindiworld.seekplays.com/#ugj5t",
                "https://animehindiworld.seekplays.com/#9eoi9",
                "https://animehindiworld.seekplays.com/#iutrn",
                "https://animehindiworld.seekplays.com/#aop5b",
                "https://animehindiworld.seekplays.com/#o1ntx",
                "https://animehindiworld.seekplays.com/#8c31z",
                "https://animehindiworld.seekplays.com/#39ado",
                "https://animehindiworld.seekplays.com/#bwecl",
                "https://animehindiworld.seekplays.com/#6mgh8",
                "https://animehindiworld.seekplays.com/#sp68i",
                "https://animehindiworld.seekplays.com/#mzy6n",
                "https://animehindiworld.seekplays.com/#h6uxn"
            ],
            "server2": []
        },
        {
            "name": "Season 2",
            "server1": [
                "https://animehindiworld.seekplays.com/#ltcxh",
                "https://animehindiworld.seekplays.com/#1xrwc",
                "https://animehindiworld.seekplays.com/#bwea3",
                "https://animehindiworld.seekplays.com/#9eoto",
                "https://animehindiworld.seekplays.com/#gyvpy",
                "https://animehindiworld.seekplays.com/#6mgt5",
                "https://animehindiworld.seekplays.com/#kshry",
                "https://animehindiworld.seekplays.com/#vdqml",
                "https://animehindiworld.seekplays.com/#39alw",
                "https://animehindiworld.seekplays.com/#mzyof",
                "https://animehindiworld.seekplays.com/#8c3r6",
                "https://animehindiworld.seekplays.com/#pnm91",
                "https://animehindiworld.seekplays.com/#5as8p",
                "https://animehindiworld.seekplays.com/#tjbhe",
                "https://animehindiworld.seekplays.com/#xhizq",
                "https://animehindiworld.seekplays.com/#6mmjs",
                "https://animehindiworld.seekplays.com/#cb95l",
                "https://animehindiworld.seekplays.com/#iut8y",
                "https://animehindiworld.seekplays.com/#ugjsb",
                "https://animehindiworld.seekplays.com/#5as83",
                "https://animehindiworld.seekplays.com/#sp6ii",
                "https://animehindiworld.seekplays.com/#h6u5v",
                "https://animehindiworld.seekplays.com/#bwwoa",
                "https://animehindiworld.seekplays.com/#ef1po",
                "https://animehindiworld.seekplays.com/#iutkg",
                "https://animehindiworld.seekplays.com/#sp6is"
            ],
            "server2": []
        },
        {
            "name": "Season 3",
            "server1": [
                "https://animehindiworld.seekplays.com/#sp6hh",
                "https://animehindiworld.seekplays.com/#5aslo",
                "https://animehindiworld.seekplays.com/#mzyeq",
                "https://animehindiworld.seekplays.com/#h6u3y",
                "https://animehindiworld.seekplays.com/#jvwpc",
                "https://animehindiworld.seekplays.com/#ugjaj",
                "https://animehindiworld.seekplays.com/#tjbsw",
                "https://animehindiworld.seekplays.com/#vdqni",
                "https://animehindiworld.seekplays.com/#kshxq",
                "https://animehindiworld.seekplays.com/#1xrvt",
                "https://animehindiworld.seekplays.com/#nrzwa",
                "https://animehindiworld.seekplays.com/#gyvoz",
                "https://animehindiworld.seekplays.com/#cb93i",
                "https://animehindiworld.seekplays.com/#pnmbf",
                "https://animehindiworld.seekplays.com/#8c3xp",
                "https://animehindiworld.seekplays.com/#h6u3q",
                "https://animehindiworld.seekplays.com/#sp6cu",
                "https://animehindiworld.seekplays.com/#8c3xl",
                "https://animehindiworld.seekplays.com/#5aslc",
                "https://animehindiworld.seekplays.com/#iut5q",
                "https://animehindiworld.seekplays.com/#xhird",
                "https://animehindiworld.seekplays.com/#bwe9c",
                "https://animehindiworld.seekplays.com/#ltcks",
                "https://animehindiworld.seekplays.com/#kshxz",
                "https://animehindiworld.seekplays.com/#wqfeo",
                "https://animehindiworld.seekplays.com/#39aiv",
                "https://animehindiworld.seekplays.com/#o1njh"
            ],
            "server2": []
        },
        {
            "name": "Season 4",
            "server1": [
                "https://animehindiworld.seekplays.com/#tjp5p",
                "https://animehindiworld.seekplays.com/#xh3yy",
                "https://animehindiworld.seekplays.com/#1xdg5",
                "https://animehindiworld.seekplays.com/#6mec8",
                "https://animehindiworld.seekplays.com/#mzfbn",
                "https://animehindiworld.seekplays.com/#9eg39",
                "https://animehindiworld.seekplays.com/#ksczn",
                "https://animehindiworld.seekplays.com/#gy19w",
                "https://animehindiworld.seekplays.com/#ugoit",
                "https://animehindiworld.seekplays.com/#bwmsl",
                "https://animehindiworld.seekplays.com/#8chft",
                "https://animehindiworld.seekplays.com/#wqzp9",
                "https://animehindiworld.seekplays.com/#ltszk",
                "https://animehindiworld.seekplays.com/#h698n",
                "https://animehindiworld.seekplays.com/#spblk",
                "https://animehindiworld.seekplays.com/#aojib",
                "https://animehindiworld.seekplays.com/#vdrod",
                "https://animehindiworld.seekplays.com/#jvnak",
                "https://animehindiworld.seekplays.com/#o1vu8",
                "https://animehindiworld.seekplays.com/#iuadn",
                "https://animehindiworld.seekplays.com/#iuadb",
                "https://animehindiworld.seekplays.com/#cb6kx",
                "https://animehindiworld.seekplays.com/#nrqji",
                "https://animehindiworld.seekplays.com/#efy6b",
                "https://animehindiworld.seekplays.com/#5atru",
                "https://animehindiworld.seekplays.com/#39uxo",
                "https://animehindiworld.seekplays.com/#pnwtm"
            ],
            "server2": []
        },
        {
            "name": "Season 5",
            "server1": [
                "https://animehindiworld.seekplays.com/#9egug",
                "https://animehindiworld.seekplays.com/#o1vb5",
                "https://animehindiworld.seekplays.com/#bwm9h",
                "https://animehindiworld.seekplays.com/#h695n",
                "https://animehindiworld.seekplays.com/#kscdy",
                "https://animehindiworld.seekplays.com/#cb635",
                "https://animehindiworld.seekplays.com/#wqzgp",
                "https://animehindiworld.seekplays.com/#aojte",
                "https://animehindiworld.seekplays.com/#ugoap",
                "https://animehindiworld.seekplays.com/#h695y",
                "https://animehindiworld.seekplays.com/#mzfgf",
                "https://animehindiworld.seekplays.com/#1xdwh",
                "https://animehindiworld.seekplays.com/#bwmu3",
                "https://animehindiworld.seekplays.com/#6mea5",
                "https://animehindiworld.seekplays.com/#iuaky",
                "https://animehindiworld.seekplays.com/#h69iv",
                "https://animehindiworld.seekplays.com/#39ulm",
                "https://animehindiworld.seekplays.com/#5atlh",
                "https://animehindiworld.seekplays.com/#8chrx",
                "https://animehindiworld.seekplays.com/#ltskc",
                "https://animehindiworld.seekplays.com/#gy1of",
                "https://animehindiworld.seekplays.com/#jvnb3",
                "https://animehindiworld.seekplays.com/#5atkp",
                "https://animehindiworld.seekplays.com/#spb3i",
                "https://animehindiworld.seekplays.com/#kscdf",
                "https://animehindiworld.seekplays.com/#jvn6i",
                "https://animehindiworld.seekplays.com/#spbca",
                "https://animehindiworld.seekplays.com/#nrqec",
                "https://animehindiworld.seekplays.com/#kscxf"
            ],
            "server2": []
        },
        {
            "name": "Season 6",
            "server1": [
                "https://animehindiworld.seekplays.com/#cb9zf",
                "https://animehindiworld.seekplays.com/#39ay9",
                "https://animehindiworld.seekplays.com/#5asvq",
                "https://animehindiworld.seekplays.com/#1xr9d",
                "https://animehindiworld.seekplays.com/#gyvhj",
                "https://animehindiworld.seekplays.com/#nrzax",
                "https://animehindiworld.seekplays.com/#8c3mv",
                "https://animehindiworld.seekplays.com/#tjbqt",
                "https://animehindiworld.seekplays.com/#sp6qq",
                "https://animehindiworld.seekplays.com/#ef1ct",
                "https://animehindiworld.seekplays.com/#o1n3z",
                "https://animehindiworld.seekplays.com/#9eo8s",
                "https://animehindiworld.seekplays.com/#jvwiq",
                "https://animehindiworld.seekplays.com/#8c3mi",
                "https://animehindiworld.seekplays.com/#ugjx3",
                "https://animehindiworld.seekplays.com/#6mgkz",
                "https://animehindiworld.seekplays.com/#kshwg",
                "https://animehindiworld.seekplays.com/#iut1o",
                "https://animehindiworld.seekplays.com/#wqftc",
                "https://animehindiworld.seekplays.com/#xhiem",
                "https://animehindiworld.seekplays.com/#sp6q8",
                "https://animehindiworld.seekplays.com/#h6ufo",
                "https://animehindiworld.seekplays.com/#mzyso",
                "https://animehindiworld.seekplays.com/#h6ufb",
                "https://animehindiworld.seekplays.com/#kshwo"
            ],
            "server2": []
        },
        {
            "name": "Season 7",
            "server1": [
                "https://animehindiworld.seekplays.com/#o1vj3",
                "https://animehindiworld.seekplays.com/#8ch8l",
                "https://animehindiworld.seekplays.com/#efyge",
                "https://animehindiworld.seekplays.com/#tjpsm",
                "https://animehindiworld.seekplays.com/#6me93",
                "https://animehindiworld.seekplays.com/#vdrn5",
                "https://animehindiworld.seekplays.com/#ugouj",
                "https://animehindiworld.seekplays.com/#nrqwt",
                "https://animehindiworld.seekplays.com/#h693z",
                "https://animehindiworld.seekplays.com/#ltsls",
                "https://animehindiworld.seekplays.com/#wqzmo",
                "https://animehindiworld.seekplays.com/#5at5c",
                "https://animehindiworld.seekplays.com/#h6931",
                "https://animehindiworld.seekplays.com/#5atlj",
                "https://animehindiworld.seekplays.com/#ksc8q",
                "https://animehindiworld.seekplays.com/#xh3dd",
                "https://animehindiworld.seekplays.com/#ksc8z",
                "https://animehindiworld.seekplays.com/#iua5e",
                "https://animehindiworld.seekplays.com/#jvnph",
                "https://animehindiworld.seekplays.com/#spbch",
                "https://animehindiworld.seekplays.com/#39uin",
                "https://animehindiworld.seekplays.com/#iua5z",
                "https://animehindiworld.seekplays.com/#cb6hi",
                "https://animehindiworld.seekplays.com/#bwm6c",
                "https://animehindiworld.seekplays.com/#1xdvs",
                "https://animehindiworld.seekplays.com/#spbsu"
            ],
            "server2": []
        },
        {
            "name": "Season 8",
            "server1": [
                "https://animehindiworld.seekplays.com/#h69hq",
                "https://animehindiworld.seekplays.com/#h69hy",
                "https://animehindiworld.seekplays.com/#8ccl5",
                "https://animehindiworld.seekplays.com/#nrqna",
                "https://animehindiworld.seekplays.com/#39u3v",
                "https://animehindiworld.seekplays.com/#ksckr",
                "https://animehindiworld.seekplays.com/#sppa9",
                "https://animehindiworld.seekplays.com/#xh3xx",
                "https://animehindiworld.seekplays.com/#8ch8p",
                "https://animehindiworld.seekplays.com/#bwmbs",
                "https://animehindiworld.seekplays.com/#aojam",
                "https://animehindiworld.seekplays.com/#iuaim",
                "https://animehindiworld.seekplays.com/#9eg9e",
                "https://animehindiworld.seekplays.com/#effww",
                "https://animehindiworld.seekplays.com/#tjptw",
                "https://animehindiworld.seekplays.com/#o1voh",
                "https://animehindiworld.seekplays.com/#wqzwg",
                "https://animehindiworld.seekplays.com/#vdrvi",
                "https://animehindiworld.seekplays.com/#spbsc",
                "https://animehindiworld.seekplays.com/#gy1gz",
                "https://animehindiworld.seekplays.com/#6me6h",
                "https://animehindiworld.seekplays.com/#5at5o",
                "https://animehindiworld.seekplays.com/#ksckq",
                "https://animehindiworld.seekplays.com/#1xd1t",
                "https://animehindiworld.seekplays.com/#jvnjc",
                "https://animehindiworld.seekplays.com/#cb6c3"
            ],
            "server2": []
        },
        {
            "name": "Season 9",
            "server1": [
                "https://animehindiworld.seekplays.com/#ugg6o",
                "https://animehindiworld.seekplays.com/#mzznr",
                "https://animehindiworld.seekplays.com/#vddy3",
                "https://animehindiworld.seekplays.com/#pnnoz",
                "https://animehindiworld.seekplays.com/#aoo9w",
                "https://animehindiworld.seekplays.com/#9eebm",
                "https://animehindiworld.seekplays.com/#gyymq",
                "https://animehindiworld.seekplays.com/#5aa3s"
            ],
            "server2": []
        }
    ]
}


];
