animeList.push({
    id: "haikyuu",
    title: "Haikyuu!! (Hindi Dub)",
    poster: "https://image.tmdb.org/t/p/w500/96986.jpg",
    year: "2014",
    duration: "24m",
    rating: "8.7",
    genres: "Sports, Comedy, Drama, School",
    cast: "Ayumu Murase, Kaito Ishikawa",
    description: "Inspired after watching a volleyball ace nicknamed 'Little Giant' in action, small-statured Shoyo Hinata revives the volleyball club at his middle school. He faces off against the 'King of the Court' Tobio Kageyama, and later they both end up at Karasuno High.",
    seasons: [
        {
            name: "Season 1",
            server1: [
                "https://animehindiworld.seekplays.com/#h6by6",
                "https://animehindiworld.seekplays.com/#h6bya",
                "https://animehindiworld.seekplays.com/#nrdtz",
                "https://animehindiworld.seekplays.com/#cbpfn",
                "https://animehindiworld.seekplays.com/#kstmb",
                "https://animehindiworld.seekplays.com/#6mw8v",
                "https://animehindiworld.seekplays.com/#bwnky",
                "https://animehindiworld.seekplays.com/#o1yiv",
                "https://animehindiworld.seekplays.com/#1x8uf",
                "https://animehindiworld.seekplays.com/#wqrs5",
                "https://animehindiworld.seekplays.com/#iu9v6",
                "https://animehindiworld.seekplays.com/#kstm6",
                "https://animehindiworld.seekplays.com/#6mwiz",
                "https://animehindiworld.seekplays.com/#9em5s",
                "https://animehindiworld.seekplays.com/#wqr9c",
                "https://animehindiworld.seekplays.com/#ltayr",
                "https://animehindiworld.seekplays.com/#h6bro",
                "https://animehindiworld.seekplays.com/#cbpdf",
                "https://animehindiworld.seekplays.com/#bwn3r",
                "https://animehindiworld.seekplays.com/#vdxpf",
                "https://animehindiworld.seekplays.com/#tjoku",
                "https://animehindiworld.seekplays.com/#nrd6x",
                "https://animehindiworld.seekplays.com/#1x8jx",
                "https://animehindiworld.seekplays.com/#ugel3",
                "https://animehindiworld.seekplays.com/#5auzc"
            ],
            server2: []
        },
        {
            name: "Season 2",
            server1: [
                "https://animehindiworld.seekplays.com/#8cs13",
                "https://animehindiworld.seekplays.com/#pnvhp",
                "https://animehindiworld.seekplays.com/#mzquo",
                "https://animehindiworld.seekplays.com/#xhcnm",
                "https://animehindiworld.seekplays.com/#396r6",
                "https://animehindiworld.seekplays.com/#5aufq",
                "https://animehindiworld.seekplays.com/#gyftj",
                "https://animehindiworld.seekplays.com/#kst1g",
                "https://animehindiworld.seekplays.com/#396q9",
                "https://animehindiworld.seekplays.com/#8csvi",
                "https://animehindiworld.seekplays.com/#1x8pd",
                "https://animehindiworld.seekplays.com/#h6brb",
                "https://animehindiworld.seekplays.com/#jv1cq",
                "https://animehindiworld.seekplays.com/#5auzr",
                "https://animehindiworld.seekplays.com/#ltafd",
                "https://animehindiworld.seekplays.com/#iu9ru",
                "https://animehindiworld.seekplays.com/#spj8k",
                "https://animehindiworld.seekplays.com/#tjol9",
                "https://animehindiworld.seekplays.com/#1x8o8",
                "https://animehindiworld.seekplays.com/#gyfao",
                "https://animehindiworld.seekplays.com/#h6bxj",
                "https://animehindiworld.seekplays.com/#396db",
                "https://animehindiworld.seekplays.com/#xhcvw",
                "https://animehindiworld.seekplays.com/#spj8r",
                "https://animehindiworld.seekplays.com/#8cs11"
            ],
            server2: []
        }
    ]
});
