animeList.push({
    id: "mushoku-tensei",
    title: "Mushoku Tensei: Jobless Reincarnation (Hindi Dubbed Series)",
    poster: "https://image.tmdb.org/t/p/w500/pAlsYh0zv4vkkD3tjfpCqh3BMXC.jpg",
    year: "2021",
    duration: "24m",
    rating: "8.4",
    genres: ["Isekai", "Fantasy", "Adventure", "Drama", "Ecchi", "Magic", "Reincarnation"],
    cast: "Yumi Uchiyama, Tomokazu Sugita",
    description: "A 34-year-old NEET is killed in a traffic accident and finds himself in a world of magic. Reincarnated as Rudeus Greyrat, he resolves to become successful in his new life, discarding his past identity for a fresh start as a magical prodigy.",
    seasons: [
        {
            name: "Season 1",
            server1: [
                "https://animehindiworld.seekplays.com/#5ama5",
                "https://animehindiworld.seekplays.com/#iuw9o",
                "https://animehindiworld.seekplays.com/#mz3qy",
                "https://animehindiworld.seekplays.com/#efifj",
                "https://animehindiworld.seekplays.com/#1xt8h",
                "https://animehindiworld.seekplays.com/#6mdml",
                "https://animehindiworld.seekplays.com/#5amub",
                "https://animehindiworld.seekplays.com/#vdsxk",
                "https://animehindiworld.seekplays.com/#bwxwi",
                "https://animehindiworld.seekplays.com/#xhjhz",
                "https://animehindiworld.seekplays.com/#spyp5",
                "https://animehindiworld.seekplays.com/#9ermj",
                "https://animehindiworld.seekplays.com/#spypc",
                "https://animehindiworld.seekplays.com/#8cocd",
                "https://animehindiworld.seekplays.com/#tjfog",
                "https://animehindiworld.seekplays.com/#ksgsy",
                "https://animehindiworld.seekplays.com/#8cos9",
                "https://animehindiworld.seekplays.com/#ksgs1",
                "https://animehindiworld.seekplays.com/#ltea3",
                "https://animehindiworld.seekplays.com/#aozgo",
                "https://animehindiworld.seekplays.com/#ugqe6",
                "https://animehindiworld.seekplays.com/#cb1bk",
                "https://animehindiworld.seekplays.com/#pn8vv",
                "https://animehindiworld.seekplays.com/#gy5f1"
            ],
            server2: []
        },
        {
            name: "Season 2",
            server1: [
                "https://animehindiworld.seekplays.com/#jvk1i",
                "https://animehindiworld.seekplays.com/#iuw9y",
                "https://animehindiworld.seekplays.com/#cb1pl",
                "https://animehindiworld.seekplays.com/#h6vby",
                "https://animehindiworld.seekplays.com/#bwxn3",
                "https://animehindiworld.seekplays.com/#8cosx",
                "https://animehindiworld.seekplays.com/#wqhrp",
                "https://animehindiworld.seekplays.com/#spyji",
                "https://animehindiworld.seekplays.com/#ksgty",
                "https://animehindiworld.seekplays.com/#xhjcq",
                "https://animehindiworld.seekplays.com/#6mdw5",
                "https://animehindiworld.seekplays.com/#o1ly5",
                "https://animehindiworld.seekplays.com/#5am93",
                "https://animehindiworld.seekplays.com/#pn8nn",
                "https://animehindiworld.seekplays.com/#vdsd8",
                "https://animehindiworld.seekplays.com/#8cocu",
                "https://animehindiworld.seekplays.com/#iuwuj",
                "https://animehindiworld.seekplays.com/#nrcrh",
                "https://animehindiworld.seekplays.com/#5ama6",
                "https://animehindiworld.seekplays.com/#tjfjo",
                "https://animehindiworld.seekplays.com/#39n9e",
                "https://animehindiworld.seekplays.com/#h6v61",
                "https://animehindiworld.seekplays.com/#jvkv5",
                "https://animehindiworld.seekplays.com/#1xtx3",
                "https://animehindiworld.seekplays.com/#o1l1l"
            ],
            server2: []
        }
    ]
});
